version: "3.7"
services:
  postgres:
    image: postgres:12.19-alpine3.20
    container_name: clinica-database
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}