CREATE TABLE doctors (
    id SERIAL PRIMARY KEY,
    job VARCHAR(255) NOT NULL,
    crm VARCHAR(9) NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);